### ISSUE TITLE
[Bug]: Error locations(loca) table missing

### ISSUE THREAD

**Issue by ilanzuo** [clipturbo/clipturbo#10]
### 小视频宝版本号 | Version

0.1.0

### 平台 | Platform

macOS

### 请描述这个Bug | Describe the bug

生成视频时，出现此Error。
模板：洗脑单词云
JSON：
[
  {
    "word": "fertile",
    "translation": "肥沃的"
  }
]
Mac OS Version：15.1(24B2083)

### 出现问题的模板 | Template

洗脑单词云

### 重现步骤 | To Reproduce

如描述，模板和json配置好后，点击“生成视频”时，出现该ERROR
![image](https://github.com/user-attachments/assets/ca4549d3-364f-4e51-95c5-8a8f7fa2b8af)

### 补充说明 | Additional context

![image](https://github.com/user-attachments/assets/3863d1a9-1d3b-4979-bd12-6c45039bb4ce)

**Comment by KeJunMao** [comment]
感谢你的反馈，这是一个已知Bug，仅出现在 MacOS 的部分情况，我将在下个版本修复

**Comment by KeJunMao** [comment]
![image](https://github.com/user-attachments/assets/f3f009f4-0d77-4c42-b629-27fd217a0f05)

直到下个版本，所有 MacOS 用户需要重建字体列表后方可修复

**Comment by ilanzuo** [comment]
重新更新中文字体后，出现新Error ： NoneType'object has no attrbute' find

配置截屏和Error截屏如下图

![image](https://github.com/user-attachments/assets/f6ac2cdb-bee6-48c2-b481-0e000c14b2df)

![image](https://github.com/user-attachments/assets/7bb75a26-67f1-43e9-98bd-307c26e3fbf4)

**Comment by KeJunMao** [comment]
这是因为你的json格式不对，请优先使用智能生成方案

**Comment by ilanzuo** [comment]
确实JSON格式不对。已正常生成视频。
