### ISSUE TITLE
关于国内无法使用 EdgeTTS 的说明

### ISSUE THREAD

**Issue by KeJunMao** [clipturbo/clipturbo#3]
### 您希望的更新和改进是什么 | Update or Improve

目前，微软针对中国大陆 IP 加了一个新参数，目前还没有被 edge-tts 库支持。

https://github.com/rany2/edge-tts/issues/290

### 解决方案

以下任意一个均可

- 网关侧接入国际互联网
- 使用增强代理模式（Enhanced Mode）

**Comment by zhongtanru** [comment]
It have been soved.

**Comment by zhongtanru** [comment]
We have been excluded and left behind.
