### ISSUE TITLE
[Bug]: 单词和图片无法居中，导致显示不全

### ISSUE THREAD

**Issue by dingdingJ** [clipturbo/clipturbo#4]
### 小视频宝版本号 | Version

0.1.0-nightly.20241108

### 平台 | Platform

Windows

### 请描述这个Bug | Describe the bug

![image](https://github.com/user-attachments/assets/cf062621-d386-42c6-b872-1a65158e7d65)

**Comment by KeJunMao** [comment]
请先优先使用正方形图片

**Comment by KeJunMao** [comment]
supported! ,pls use `0.1.0-nightly.20241110`
