### ISSUE TITLE
洗脑记单词汉英对调后乱码

### ISSUE THREAD

**Issue by dingdingJ** [clipturbo/clipturbo#7]
### 您希望的更新和改进是什么 | Update or Improve

如图所示，周三变成实心框框，本想发到TikTok给外国人学中文。

![image](https://github.com/user-attachments/assets/2941d015-0716-4608-b3e5-05dd287fe1c6)

**Comment by KeJunMao** [comment]
当你将本应该显示中文的位置用于显示英文，你需要反过来设置字体
